before_install:
   - sudo mkdir -p /home/linuxbrew
   - sudo chown "$USER" /home/linuxbrew
   - git clone https://github.com/Linuxbrew/brew.git /home/linuxbrew/.linuxbrew
   - PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
   - brew update
   - brew tap mulle-kybernetik/software
   - brew install mulle-build

script:
   - DONT_ASK=YES ./mulle-objc-clone.sh https://github.com/mulle-objc
